blacklist:
  outcast: 999
  unloving: 999
  flowers: 999
  abyss: 999
  bones: 999
  time: 999
  warp: 999
  violet: 999
  dicers: 999
  wrath: 999
  sloth: 999
  flood: 999
  vain: 999
  check: 999

blacklist_cn:
  无归属: 999
  无慈悲: 999
  落花: 999
  伏行深渊: 999
  肉斩骨断: 999
  时间杀人: 999
  谋杀案: 999
  紫罗兰: 999
  斩切: 999
  压抑的: 999
  虚张声势: 999
  沉溺者: 999
  空转的: 999
  体检: 999