blacklist:
  - "outcast"
  - "unloving"
  - "flowers"
  - "abyss"
  - "bones"
  - "time"
  - "warp"
  - "violet"
  - "dicers"
  - "wrath"
  - "sloth"
  - "flood"
  - "vain"
  - "check"

blacklist_cn:
  - "无归属"
  - "无慈悲"
  - "落花"
  - "伏行深渊"
  - "肉斩骨断"
  - "时间杀人"
  - "谋杀案"
  - "紫罗兰"
  - "斩切"
  - "压抑的"
  - "虚张声势"
  - "沉溺者"
  - "空转的"
  - "体检"
