# 游戏设置
game_title_name: LimbusCompany # 游戏窗口标题。
game_process_name: LimbusCompany # 游戏进程名。

game_path: C:\Program Files (x86)\Steam\steamapps\common\Limbus Company\LimbusCompany.exe # 游戏启动路径。
auto_set_game_path: True # 是否自动设置游戏路径

language_in_game: en # 游戏语言
after_completion: 0 # 脚本结束后的操作
language_in_program: en # 程序语言

clean_logs: False # 是否自动清理日志

# 脚本运行速度设置
screenshot_interval: 0.85    # 截图间隔时间
mouse_action_interval : 0.5  # 鼠标操作间隔时间

resonate_with_Ahab: False # 是否播放亚哈语录

# 自动更新
check_update: True
update_source: GitHub # 更新源
mirrorchyan_cdk: "" # Mirror酱 CDK

# 保存启动后的页面
default_page: 0

# 是否进行自动窗口设置
set_windows: True # 是否进行自动窗口设置
set_win_size: 1080 # 设置使用的分辨率,1080:1920*1080,1440:2560*1440,2160:3840*2160,720:1280*720,900:1600*900,1800:3200*1800
set_win_position: True # 是否自动设置窗口的位置
set_reduce_miscontact: True # 是否防止误触

# 是否进行日常本
daily_task: False # 是否进行日常本
set_EXP_count: 1 # 设置经验本的次数
set_thread_count: 3 # 设置纽本的次数
daily_teams: 1 # 设置日常本使用的队伍
targeted_teaming_EXP: False
EXP_day_1_2: 1
EXP_day_3_4: 1
EXP_day_5_6: 1
EXP_day_7: 1
targeted_teaming_thread: False
thread_day_1: 1
thread_day_2: 1
thread_day_3: 1
thread_day_4: 1
thread_day_5: 1
thread_day_6: 1
thread_day_7: 1

# 是否自动获取奖励
get_reward: False # 是否进行获取奖励
set_get_prize: 0 # 0 领取邮件和通行证日常与周常，1 只领取通行证日常与周常， 2 只领取邮件

# 是否自动购买体力
buy_enkephalin: False # 是否自动购买体力
set_lunacy_to_enkephalin: 2 # 0 不购买，1 购买一次，2 购买两次
Dr_Grandet_mode: False

# 是否进行自动镜牢
mirror: False # 是否进行自动镜牢
set_mirror_count: 1 # 镜牢的次数
hard_mirror: False # 进行困难镜牢
no_weekly_bonuses: False # 不使用每周加成
flood_3_exit: False # 只打三层
infinite_dungeons: False # 无限刷牢
save_rewards : False # 保存奖励不领
hard_mirror_single_bonuses: True # 困难镜牢使用单次加成
teams_be_select_num: 0 # 被选中的队伍数量
teams_be_select: [False] # 被选中的队伍
teams_order: [0] # 队伍的顺序


# 一号队伍设置
team1_setting:
  team_system: 0 # 队伍使用的体系
  team_number: 1 # 使用的队伍序号
  shop_strategy: 0 # 商店策略
  sinners_be_select: 0 # 有几名罪人被选中
  chosen_sinners: [0,0,0,0,0,0,0,0,0,0,0,0] # 有哪几名罪人被选中
  sinner_order: [0,0,0,0,0,0,0,0,0,0,0,0] # 罪人被选中的顺序
  system_burn: False # 弃置燃烧饰品
  system_bleed: False # 弃置流血饰品
  system_tremor: False # 弃置震颤饰品
  system_rupture: False # 弃置破裂饰品
  system_poise: False # 弃置呼吸饰品
  system_sinking: False # 弃置沉沦饰品
  system_charge: False # 弃置充能饰品
  system_slash: False # 弃置斩击饰品
  system_pierce: False # 弃置穿刺饰品
  system_blunt: False # 弃置打击饰品
  do_not_heal: False # 不治疗
  do_not_buy: False # 不购买
  do_not_fuse : False # 不合成
  do_not_sell: False # 不出售
  do_not_enhance: False # 不升级
  only_aggressive_fuse : False # 合成只采取激进策略
  do_not_system_fuse : False # 不合成体系饰品
  only_system_fuse : False # 只合成体系饰品
  avoid_skill_3 : False # 避免使用3技能
  re_formation_each_floor : False # 每个楼层重新编队
  keep_starlight: False # 保留开局星光——————————————————————————————————
  reward_cards : False # 奖励卡优先度
  reward_cards_select: 0 # 自定义奖励卡优先度
  choose_opening_bonus : False # 自选开局加成
  opening_bonus_select: 0 # 开局加成已选数量
  opening_bonus: [0,0,0,0,0,0,0,0,0,0] # 启用的开局加成
  opening_bonus_order: [0,0,0,0,0,0,0,0,0,0] # 启用的开局加成顺序
  after_level_IV : False # 自定义合成四级后的操作
  after_level_IV_select : 0 # 合成四级后的操作
  shopping_strategy : False # 自定义购物策略
  shopping_strategy_select: 0 # 购物策略
  opening_items : False # 自定义开局道具
  opening_items_select : 0 # 开局道具体系
  opening_items_system : 0 # 开局道具选择顺序
  second_system : False # 启用第二体系
  second_system_select : 0 # 第二体系
  second_system_setting : 0 # 第二体系启用时间
  second_system_action : [0,0,0,0] # 第二体系行动模式
  skill_replacement : False # 自定义技能替换
  skill_replacement_select : 0 # 技能替换设置
  skill_replacement_mode : 0 # 技能替换模式
  ignore_shop : [0,0,0,0,0] # 忽略商店楼层

team1_remark_name: # 队伍备注名