# 保存最后处在的页面
default_page: 2

# 保存各个任务是否启用
set_windows: true
daily_task: false
get_reward: false
buy_enkephalin: false
mirror: false

# 保存"窗口设置"任务模块中的设置
set_win_size: 0  #窗口大小设置
set_win_position: 0  #窗口位移设置
set_reduce_miscontact: 0  #结束时是否恢复窗口

# 保存"日常任务"任务模块中的设置
set_EXP_count: 1  #经验本次数
set_thread_count: 3 #纽本次数
all_teams: 1 #日常任务使用哪支队伍

# 保存"领取奖励"任务模块中的设置
set_get_prize: 0  #领取日常、周常、邮件奖励设置

# 保存"狂气换体"任务模块中的设置
set_lunacy_to_enkephalin: 2 #狂气换体次数设置

# 保存"镜牢设置"任务模块中的设置，这部分的内容不可随意修改，否则会闪退！！！！！
set_mirror_count: 1  #坐牢次数设置
team1: false    #设置配队1是否启用
team2: false   #设置配队2是否启用
team3: false   #设置配队3是否启用
team4: false   #设置配队4是否启用
team5: false   #设置配队5是否启用
team6: false   #设置配队6是否启用
team7: false   #设置配队7是否启用
teams_be_select: 0  #保存启用了几个队伍
team1_order: ''  #设置配队1的顺序
team2_order: ''  #设置配队2的顺序
team3_order: ''   #设置配队3的顺序
team4_order: ''   #设置配队4的顺序
team5_order: ''   #设置配队5的顺序
team6_order: ''   #设置配队6的顺序
team7_order: ''   #设置配队7的顺序

#保存各个配队情况
team1_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                                            #各体系
}
team2_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                              #各体系
}
team3_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                                            #各体系
}
team4_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                                            #各体系
}
team5_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                                            #各体系
}
team6_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                                            #各体系
}
team7_setting: {all_system: 0, all_teams: 1, sinners_be_select: 0, YiSang: false,
  YiSang_order: '', Faust: false, Faust_order: '', DonQuixote: false, DonQuixote_order: '',
  Ryoshu: false, Ryoshu_order: '', Meursault: false, Meursault_order: '', HongLu: false,
  HongLu_order: '', Heathcliff: false, Heathcliff_order: '', Ishmael: false, Ishmael_order: '',
  Rodion: false, Rodion_order: '', Sinclair: false, Sinclair_order: '', Outis: false,
  Outis_order: '', Gregor: false, Gregor_order: '', fuse: false, burn: false, bleed: false,
  tremor: false, rupture: false, poise: false, sinking: false, charge: false, slash: false,
  clash: false, blunt: false                                                            #各体系
}
