name: Build realtime release

# 触发条件：手动触发或推送触发
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"

# 权限设置：需要写入仓库内容的权限
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      # 步骤1：签出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "false"

      # 步骤2：设置Python环境
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: "pip"

      # 步骤3：安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # 步骤4：生成并打包项目
      - name: Build executable & Bundle resources
        run: |
          pyinstaller main.spec
          mkdir dist_release
          mv dist/* dist_release/
          cp -r 3rdparty dist_release/AALC/
          cp -r pic dist_release/AALC/
          cp -r doc dist_release/AALC/
          cp LICENSE dist_release/AALC/
          cp README.md dist_release/AALC/
          7z a -mx=7 AALC_${{ github.run_number }}.7z dist_release/*

      # 步骤5：上传压缩包
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AALC_${{ github.run_number }}.7z
          path: |
            AALC_${{ github.run_number }}.7z
