name: Reusable Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 签出代码
      - name: Checkout
        uses: actions/checkout@main

      # 配置 uv 
      - name: Setup UV for Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock

      # 安装依赖
      - name: Install dependencies
        run: |
          uv sync --frozen
      
      # 构建并打包程序
      - name: build & bundle
        run: |
          uv run python ./build.py --version ${{ inputs.version }}

      # 上传打包结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: AALC_${{ inputs.version }}
          path: |
            dist/AALC_${{ inputs.version }}.7z
